name: Docker Publish Pipeline

on:
  push:
    branches:
      - main  # Déclenche le workflow lors d'un push sur la branche `main`

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Le job sera exécuté sur un environnement Ubuntu

    steps:
    # Étape 1: Vérifier le code source depuis le dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2: Configurer Docker Buildx pour la construction de l'image
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Étape 3: Se connecter à Docker Hub avec les secrets GitHub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Utiliser le secret Docker Hub
        password: ${{ secrets.DOCKER_PASSWORD }}  # Utiliser le secret Docker Hub

    # Étape 4: Construire et pousser l'image Docker vers Docker Hub
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .  # Utilise le répertoire actuel comme contexte de construction
        push: true  # Pousse l'image sur Docker Hub
        tags: fatfat23001/tic_tac_toe:latest  # Tag de l'image Docker
